const DEFAULT_API_URL = "https://backend-production-53dd.up.railway.app";
const $ = (id) => document.getElementById(id);
let articleStatusTimer;

document.addEventListener("DOMContentLoaded", async () => {
  const settings = await chrome.storage.local.get({ apiUrl: DEFAULT_API_URL, apiToken: "" });
  $("apiUrl").value = settings.apiUrl; $("apiToken").value = settings.apiToken;
  document.querySelectorAll(".tab").forEach((tab) => tab.onclick = () => activateTab(tab.dataset.tab));
  $("saveSettings").onclick = () => void saveSettings(); $("testConnection").onclick = () => void testConnection();
  $("manualScan").onclick = () => void manualScan();
  $("captureCurrent").onclick = () => void captureCurrent(); $("prepareReplies").onclick = () => void prepareReplies(); $("openNext").onclick = () => void openNext();
  $("startProfile").onclick = () => void startProfile(); $("stopProfile").onclick = () => void stopProfile(); $("importArticles").onclick = () => void importArticles(); $("capturePage").onclick = () => void capturePage();
  $("addRule").onclick = () => void addRule(); $("refresh").onclick = () => void refreshAll(); $("deleteAll").onclick = () => void deleteAll();
  if (settings.apiToken) {
    activateTab("capture");
    await refreshAll();
  } else {
    activateTab("settings");
  }
});

async function api(path, init) { const response = await chrome.runtime.sendMessage({ type: "QUILL_API", path, init }); if (!response?.ok) throw new Error(response?.error || "Could not reach Quill."); return response.data; }
async function saveSettings() { await chrome.storage.local.set({ apiUrl: $("apiUrl").value.trim(), apiToken: $("apiToken").value.trim() }); setStatus("connectionStatus", "Saved locally in this browser."); }
async function testConnection() { try { await saveSettings(); await api("/research/items?limit=1"); setStatus("connectionStatus", "Connected to your Quill research inbox."); activateTab("capture"); await refreshAll(); } catch (error) { setStatus("connectionStatus", error.message); } }
function activateTab(name) { document.querySelectorAll(".tab").forEach((tab) => tab.classList.toggle("active", tab.dataset.tab === name)); document.querySelectorAll(".panel").forEach((panel) => panel.classList.toggle("active", panel.id === `panel-${name}`)); }
async function activeXTab() { const [tab] = await chrome.tabs.query({ active: true, currentWindow: true }); if (!tab?.id || !/^https:\/\/(x|twitter)\.com\//.test(tab.url || "")) throw new Error("Open an X page first."); return tab.id; }
async function sendToTab(type, payload = {}) { const tabId = await activeXTab(); try { return await chrome.tabs.sendMessage(tabId, { type, ...payload }); } catch { await chrome.scripting.executeScript({ target: { tabId }, files: ["content.js"] }); return chrome.tabs.sendMessage(tabId, { type, ...payload }); } }
async function captureCurrent() { try { const { item } = await sendToTab("QUILL_CAPTURE_CURRENT"); if (!item) throw new Error("No X post found."); await api("/research/items", { method: "POST", body: item }); setStatus("scanStatus", "Saved current post."); await refreshAll(); } catch (error) { setStatus("scanStatus", error.message); } }
async function manualScan() { try { $("scanBadge").textContent = "Saving"; setStatus("scanStatus", "Checking the posts currently on screen…"); const result = await sendToTab("QUILL_MANUAL_SCAN"); if (!result?.ok) throw new Error(result?.error || "Could not scan this page."); const posts = result.inspected === 1 ? "post" : "posts"; const matches = result.saved === 1 ? "match" : "matches"; setStatus("scanStatus", `Saved ${result.saved} ${matches} from ${result.inspected} visible ${posts}.`); await refreshAll(); } catch (error) { setStatus("scanStatus", error.message); } finally { $("scanBadge").textContent = "Ready"; } }
async function prepareReplies() { try { setStatus("queueStatus", "Preparing replies in Quill…"); const result = await api("/research/prepare", { method: "POST", body: { limit: 5 } }); const failures = result.errors?.length ? ` (${result.errors.length} need attention)` : ""; setStatus("queueStatus", `Ready: ${result.prepared}. Skipped: ${result.skipped}.${failures}`); await refreshAll(); return result; } catch (error) { setStatus("queueStatus", error.message); throw error; } }
async function openNext() { try { await prepareReplies(); const { items } = await api("/research/quick-next", { method: "POST", body: { limit: 5 } }); if (!items.length) { setStatus("queueStatus", "No prepared replies are waiting."); return; } for (const item of items) await chrome.tabs.create({ url: item.url, active: false }); setStatus("queueStatus", `Opened ${items.length} ready replies. Use the Quill Reply button on each post.`); await refreshAll(); } catch {} }
async function startProfile() { try { const result = await sendToTab("QUILL_START_PROFILE"); setStatus("extractStatus", result.status === "started" ? "Collecting. The count is visible on the right side of X while you scroll." : `Already collecting ${result.count} posts.`); } catch (error) { setStatus("extractStatus", error.message); } }
async function stopProfile() { try { const result = await sendToTab("QUILL_STOP_PROFILE"); if (!result.items?.length) throw new Error("No posts captured. Scroll the profile before stopping."); const saved = await saveInBatches(result.items); await sendToTab("QUILL_PROFILE_SAVE_COMPLETE", { saved, total: result.items.length }); setStatus("extractStatus", `Saved ${saved} profile posts to Quill research.`); await refreshAll(); } catch (error) { await sendToTab("QUILL_PROFILE_SAVE_ERROR", { error: error.message }).catch(() => {}); setStatus("extractStatus", error.message); } }
async function saveInBatches(items) { const batchSize = 100; let saved = 0; for (let index = 0; index < items.length; index += batchSize) { const batch = items.slice(index, index + batchSize); const result = await api("/research/items/bulk", { method: "POST", body: batch }); saved += result.count; setStatus("extractStatus", `Saving ${saved} of ${items.length} profile posts…`); await sendToTab("QUILL_PROFILE_SAVE_PROGRESS", { saved, total: items.length }); } return saved; }
async function importArticles() { try { const tabId = await activeXTab(); let result = await sendToTab("QUILL_IMPORT_ARTICLES"); if (result.status === "needs_articles_tab") { setStatus("extractStatus", "Opening this profile’s Articles tab…"); await chrome.tabs.update(tabId, { url: result.articlesUrl }); await waitForTabComplete(tabId); await new Promise((resolve) => setTimeout(resolve, 1200)); result = await sendToTab("QUILL_IMPORT_ARTICLES"); } if (result.status === "invalid_page") throw new Error(result.error); if (result.status === "already_running") { setStatus("extractStatus", `Importing articles: ${result.saved} saved so far.`); } else { setStatus("extractStatus", "Finding articles on this profile. Keep the Articles tab open."); } clearInterval(articleStatusTimer); articleStatusTimer = setInterval(() => void refreshArticleImportStatus(), 1000); } catch (error) { setStatus("extractStatus", error.message); } }
function waitForTabComplete(tabId, timeoutMs = 20_000) { return new Promise((resolve, reject) => { let settled = false; const finish = (callback, value) => { if (settled) return; settled = true; clearTimeout(timeout); chrome.tabs.onUpdated.removeListener(onUpdated); callback(value); }; const timeout = setTimeout(() => finish(reject, new Error("Articles tab took too long to load.")), timeoutMs); const onUpdated = (updatedTabId, info) => { if (updatedTabId === tabId && info.status === "complete") finish(resolve); }; chrome.tabs.onUpdated.addListener(onUpdated); chrome.tabs.get(tabId).then((tab) => { if (tab.status === "complete") finish(resolve); }).catch(() => finish(reject, new Error("Articles tab was closed."))); }); }
async function refreshArticleImportStatus() { try { const status = await sendToTab("QUILL_ARTICLES_STATUS"); if (status.error) { clearInterval(articleStatusTimer); setStatus("extractStatus", status.error); return; } if (status.running) { setStatus("extractStatus", status.total ? `Importing ${status.saved} of ${status.total} articles…` : `Finding articles: ${status.found} found…`); return; } clearInterval(articleStatusTimer); if (status.total || status.saved || status.failed) { setStatus("extractStatus", `Imported ${status.saved} articles${status.failed ? `; ${status.failed} could not be read.` : "."}`); await refreshAll(); } } catch (error) { clearInterval(articleStatusTimer); setStatus("extractStatus", error.message); } }
async function capturePage() { try { const { item } = await sendToTab("QUILL_CAPTURE_PAGE"); await api("/research/items", { method: "POST", body: item }); setStatus("extractStatus", "Saved page to Quill research."); await refreshAll(); } catch (error) { setStatus("extractStatus", error.message); } }
async function addRule() { try { const value = $("ruleValue").value.trim(); if (!value) return; await api("/research/rules", { method: "POST", body: { kind: $("ruleKind").value, value } }); $("ruleValue").value = ""; setStatus("keywordStatus", "Keyword saved."); await loadRules(); void sendToTab("QUILL_RELOAD_RULES").catch(() => {}); } catch (error) { setStatus("keywordStatus", error.message); } }
async function refreshAll() { await Promise.all([loadRules(), loadItems()]); }
async function loadRules() { try { const { rules } = await api("/research/rules"); const target = $("rules"); target.replaceChildren(...rules.map((rule) => { const node = document.createElement("span"); node.className = `rule ${rule.kind.toLowerCase()}`; node.textContent = `${rule.kind.toLowerCase()}: ${rule.value}`; return node; })); } catch (error) { $("rules").textContent = error.message; } }
async function deleteAll() { if (!confirm("Delete every item from your Quill reply queue? This does not affect X.")) return; try { const { archived } = await api("/research/items", { method: "DELETE" }); setStatus("queueStatus", `Deleted ${archived} queue item${archived === 1 ? "" : "s"}.`); await refreshAll(); } catch (error) { setStatus("queueStatus", error.message); } }
async function loadItems() { try { const { items } = await api("/research/items?limit=50"); const badge = $("replyCount"); badge.textContent = String(items.length); badge.setAttribute("aria-label", `${items.length} total queued items`); badge.classList.toggle("hidden", items.length === 0); $("queueTotal").textContent = `${items.length} total`; const target = $("items"); target.replaceChildren(); if (!items.length) { target.textContent = "No reply candidates yet. Scan the feed first."; return; } for (const item of items) target.append(renderItem(item)); } catch (error) { $("items").textContent = error.message; } }
function renderItem(item) { const node = document.createElement("article"); node.className = "item"; const reply = item.generatedReply; node.innerHTML = `<div class="item-head">${escape(item.sourceHandle ? `@${item.sourceHandle}` : item.type)} · ${escape(item.status)}</div><div class="item-text">${escape(item.text || item.title || "Untitled capture")}</div><div class="item-footer">${reply?.text ? "Reply ready" : "Awaiting reply"}</div>`; const footer = node.querySelector(".item-footer"); const open = document.createElement("button"); open.className = "copy"; open.textContent = reply?.text ? "Open + copy" : "Prepare + open"; open.onclick = async () => { try { open.disabled = true; open.textContent = "Preparing…"; let prepared = reply; if (!prepared?.text) { const result = await api(`/research/items/${item.id}/prepare`, { method: "POST" }); prepared = result.reply; } if (!prepared?.text) throw new Error("No natural reply angle for this post."); await navigator.clipboard.writeText(prepared.text); await api(`/research/replies/${prepared.id}/copied`, { method: "POST" }); await chrome.tabs.create({ url: item.url, active: true }); setStatus("queueStatus", "Reply copied. Paste it into the X post you just opened."); await refreshAll(); } catch (error) { open.textContent = error.message === "No natural reply angle for this post." ? "No angle" : "Unavailable"; setTimeout(() => { open.textContent = reply?.text ? "Open + copy" : "Prepare + open"; open.disabled = false; }, 1600); } }; const remove = document.createElement("button"); remove.className = "secondary compact danger"; remove.textContent = "Delete"; remove.onclick = async () => { try { await api(`/research/items/${item.id}`, { method: "DELETE" }); node.remove(); setStatus("queueStatus", "Deleted from your queue."); await refreshAll(); } catch (error) { setStatus("queueStatus", error.message); } }; footer.append(open, remove); return node; }
function setStatus(id, message) { $(id).textContent = message || ""; }
function escape(value) { const node = document.createElement("span"); node.textContent = value || ""; return node.innerHTML; }
